### ISSUE TITLE
https://registry.bazel.build/modules/protobuf-matchers does not compile

### ISSUE THREAD

**Issue by shixiong-jiang** [inazarenko/protobuf-matchers#10] opened 2024-10-10 06:39 UTC
Hello Igor,

https://registry.bazel.build/modules/protobuf-matchers doesn't compile. 

I got below error:
```
external/protobuf-matchers~/protobuf-matchers/protocol-buffer-matchers.h:218:1: note: 'std::setprecision' is defined in header '<iomanip>'; did you forget to '#include <iomanip>'?
```

I guess this change is not included 
https://github.com/inazarenko/protobuf-matchers/commit/ca86ada58d902b1b8c89ed259672f1b3019fc92e

Could you plz upload a newer version to the bazel modules? 

Thanks,

**Comment by inazarenko** [comment] 2024-10-10 21:45
Could you add instructions to reproduce? Which toolchain are you using?

**Comment by shixiong-jiang** [comment] 2024-10-10 22:27
Hello Igor,

## Timestamp

This fix https://github.com/inazarenko/protobuf-matchers/commit/ca86ada58d902b1b8c89ed259672f1b3019fc92e was submitted on Jun 19 2024.

https://registry.bazel.build/modules/protobuf-matchers version is June 03 2024. 

From the timestamp, it most possibly doesn't include above fix. 

## A small test to reproduce the error.

### MODULE.bazel
```
bazel_dep(name = "rules_cc", version = "0.0.10")
bazel_dep(name = "googletest", version = "1.15.2")
bazel_dep(name = "protobuf", version = "28.1")
bazel_dep(name = "protobuf-matchers",  version = "0.0.0-20240603-9f688b0")
```

### BUILD
```
cc_test(
    name = "foo_test",
    srcs = ["foo_test.cc"],
    deps = [
        "@googletest//:gtest_main",
        "@protobuf//:protobuf",
        "@protobuf-matchers//protobuf-matchers",
    ],
)
```

### foo_test.cc

```
#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "protobuf-matchers/protocol-buffer-matchers.h"

namespace foo {
namespace {

using ::protobuf_matchers::EquivToProto;

TEST(Foo, Bar) {
//EXPECT_THAT(got, EquivToProto(want));
}

}  // namespace
}  // namespace foo
```

BUILD
```
bazel build --cxxopt=-std=c++17 :foo_test
```
SUCCEED

But 

```
bazel build --cxxopt=-std=c++14 :foo_test
```
FAILED

## In my real code.

In fact, I added `build --cxxopt="-std=c++17"` to the .bazelrc.
But, I am uncertain, why in the error message, it still says `c++14`

```
gcc failed: error executing CppCompile command (from target //:shixiong_test) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++14' -MD -MF ... (remaining 114 arguments skipped)
```
I am debugging it... 

If you upload a new version, I guess both c++17 and c++14 will work. 
I am using WORKSPACE.bazel, which download the latest version. Everything compiles.

Thx.

**Comment by inazarenko** [comment] 2024-10-10 22:40
> I guess both c++17 and c++14 will work.

C++14 won't work because, if nothing else, `<string_view>` requires C++17. 

That said, I will try to upload a new version (all registry stuff was contributed by other folks, so I have to figure out how it actually works).

**Comment by shixiong-jiang** [comment] 2024-10-10 22:42
Ack. Thx a lot

**Comment by inazarenko** [comment] 2024-10-11 13:54
https://github.com/bazelbuild/bazel-central-registry/pull/2937 merged. Let me know if I can help with anything else.

**Closed as completed by inazarenko** 2024-10-11 13:54 UTC

**Comment by shixiong-jiang** [comment] 2024-10-11 17:49
Cool. Thx. The new version works!
